//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Arkaham.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users
    {
        public int Id_user { get; set; }
        public string Email { get; set; }
        public string Name { get; set; }
        public string GID { get; set; }
        public Nullable<int> Department { get; set; }
        public Nullable<int> Role { get; set; }
    
        public virtual Department Department1 { get; set; }
        public virtual Role Role1 { get; set; }
    }
}
